name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Create env file
      run: |
        touch .env
        echo TRIPLE_STORE_PROTOCOL="http" >> .env
        echo DEFAULT_GRAPH="http://www.data4knowledge/graphs/test" >> .env
        cat .env
        
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Fuseki Triple Store
      run: |
          docker run -d -p 3030:3030 daveih/fuseki:v3.16.0 --loc ds --update /test

    - name: Sleep
      uses: juliangruber/sleep-action@v1
      with:
        time: 15s
    
    - name: Run tests
      run: |
        pytest tests/

